version: "2.1"

services:
  db:
    image: wnameless/oracle-xe-11g-r2
    environment:
      ORACLE_ALLOW_REMOTE: "true"
    #volumes:
    #  - ./ddl_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql You can uncomment this in order to specify some DB init script
    ports:
      - "49161:1521"
      - "49162:8080"
  web:
    image: jboss/wildfly
    ports:
      - "8888:8080"
    volumes:
#      - ./target:/opt/jboss/wildfly/standalone/deployments/
      - ./libs:/opt/jboss/wildfly/standalone/deployments/
      - ./schema.xsd:/opt/jboss/schema.xsd
    links:
      - db
