version: "2.1"

services:
  db:
    image: wnameless/oracle-xe-11g-r2
    environment:
      ORACLE_ALLOW_REMOTE: "true"
    #volumes:
    #  - ./ddl_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql You can uncomment this in order to specify some DB init script
    ports:
      - "49161:1521"
  web:
    image: tomcat:latest
    environment:
      JPDA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    ports:
      - "8888:8080"
      - "8000:8000"
    volumes:
      - ./target/:/usr/local/tomcat/webapps/
      - ./tomcat_logs:/usr/local/tomcat/logs
    links:
      - db
    command: /usr/local/tomcat/bin/catalina.sh jpda run
